# Generated by Django 4.1.1 on 2022-11-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=7)),
                ('Phone_Number', models.PositiveBigIntegerField()),
                ('Email_Address', models.EmailField(max_length=254)),
                ('Address', models.TextField(max_length=80)),
                ('Date_Of_Birth', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
