# Generated by Django 4.1.1 on 2022-11-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='Date_Of_Birth',
            field=models.DateField(blank=True, null=True, verbose_name='format: (mm/dd/yyyy'),
        ),
    ]
