# Generated by Django 4.1.1 on 2022-11-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_jobmodel_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job1Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Age', models.PositiveIntegerField()),
                ('Gender', models.CharField(max_length=7)),
                ('Phone_Number', models.PositiveBigIntegerField()),
                ('Email_Address', models.EmailField(max_length=254)),
                ('Address', models.TextField(max_length=80)),
                ('Date_Of_Birth', models.DateField(blank=True, null=True, verbose_name='DOB: (yyyy/mm/dd)')),
            ],
        ),
        migrations.DeleteModel(
            name='JobModel',
        ),
    ]
