# Generated by Django 4.1.1 on 2022-11-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_job1model_delete_jobmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='job1model',
            name='time_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
