# Generated by Django 4.1.1 on 2022-11-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_job1model_time_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job1model',
            name='time_date',
        ),
        migrations.AddField(
            model_name='job1model',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job1model',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
